PersonalWebTool_V1.2/Models/Habit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Models
{
    public class Habit
    {
        public int HabitID { get; set; }
        public string Name { get; set; }
        public int Points { get; set; }
    }
}

PersonalWebTool_V1.2/Models/HabitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Models
{
    public class HabitViewModel
    {
        public List<HabitDay> HabitDays { get; set; }
        public List<Habit> Habits { get; set; }
        public List<HabitQuantity> HabitQuantities { get; set; }
    }
}

PersonalWebTool_V1.2/Areas/Admin/Controllers/HabitController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebTool_V1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HabitController : AdminController
    {
        private BlogContext context;
        public HabitController(BlogContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            List<Habit> habits = context.Habits.OrderBy(h => h.Name).ToList();
            return View(habits);
        }
        [HttpGet]
        public IActionResult Add()
        {
            Habit habit = new Habit();
            ViewBag.Action = "Add";
            return View("AddUpdate", habit);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            Habit habit = context.Habits.Find(id);
            ViewBag.Action = "Update";
            return View("AddUpdate", habit);
        }

        [HttpPost]
        public IActionResult Update(Habit habit)
        {
            if(ModelState.IsValid)
            {
                if(habit.HabitID == 0)
                {
                    context.Habits.Add(habit);
                    context.SaveChanges();
                    foreach(HabitDay habitDay in context.HabitDays)
                    {
                        //habitDay.HabitQuantities = context.HabitDays.Find(habitDay.HabitDayID).HabitQuantities;
                        HabitQuantity habitQuantity = new HabitQuantity();
                        habitQuantity.Habit = habit;
                        habitQuantity.HabitDay = habitDay;
                        habitQuantity.Counter = 0;
                        habitQuantity.HabitQuantityID = habit.HabitID + "-" + habitDay.HabitDayID;
                        context.Add(habitQuantity);
                        habitDay.HabitQuantities.Add(habitQuantity);
                    }
                }
                else
                {
                    context.Habits.Update(habit);
                }
                context.SaveChanges();
                return RedirectToAction("List");
            }
            else
            {
                return View("AddUpdate", habit);
            }
        }
        

    }
}

PersonalWebTool_V1.2/Areas/Admin/Views/Habit/AddUpdate.cshtml
@model Habit

@{
    string title = ViewBag.Action + " habit";
    ViewBag.Title = title;
}

<h1>@ViewBag.Title</h1>

<form autocomplete="off" method="post" asp-area="Admin" asp-controller="Habit" asp-action="Update">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="HabitID" />
    <div class="form-group">
        <label asp-for="Name">Habit:</label>
        <input asp-for="Name" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Points">Points:</label>
        <input asp-for="Points" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="Habit" asp-action="List" class="btn btn-primary">Cancel</a>
</form>

PersonalWebTool_V1.2/Areas/Admin/Views/Habit/List.cshtml
@model List<Habit>
@{ViewBag.Title = "Habit Manager";}

<h1>@ViewBag.Title</h1>
<div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Points</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Habit habit in Model)
            {
                <tr>
                    <td>@habit.Name</td>
                    <td>@habit.Points</td>
                    <td>
                        <a asp-controller="Habit" asp-action="Update" asp-route-id="@habit.HabitID">Update</a>
                    </td>
                    <td>
                        <a asp-controller="Habit" asp-action="Delete" asp-route-id="@habit.HabitID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="Habit" asp-action="Add" class="btn btn-primary">Add New Habit</a>
</div>