PersonalWebTool_V1.2/Models/GratefulnessViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Models
{
    public class GratefulnessViewModel
    {
        public GratefulnessEntry GratefulnessEntry { get; set; }
        public List<GratefulnessUnit> GratefulnessUnits { get; set; }
    }
}

PersonalWebTool_V1.2/Areas/Admin/Controllers/GratefulnessController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalWebTool_V1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GratefulnessController : AdminController
    {
        private BlogContext context;
        public GratefulnessController(BlogContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            List<GratefulnessEntry> entries = context.GratefulnessEntries.Include(entry => entry.GratefulnessUnits).OrderByDescending(entry => entry.DateCreated).ToList();
            return View(entries);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";

            GratefulnessViewModel model = new GratefulnessViewModel();
            model.GratefulnessEntry = new GratefulnessEntry();
            List<GratefulnessUnit> units = new List<GratefulnessUnit> {
                new GratefulnessUnit(),
                new GratefulnessUnit(),
                new GratefulnessUnit(),
                new GratefulnessUnit(),
                new GratefulnessUnit()};
            model.GratefulnessUnits = units;
            return View("AddUpdate", model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.Action = "Update";

            GratefulnessEntry entry = context.GratefulnessEntries.Find(id);
            List<GratefulnessUnit> units = context.GratefulnessUnits.Where(u => u.GratefulnessEntryID == entry.GratefulnessEntryID).ToList();
            GratefulnessViewModel model = new GratefulnessViewModel();
            model.GratefulnessEntry = entry;
            model.GratefulnessUnits = units;
            return View("AddUpdate", model);
        }

        [HttpPost]
        public IActionResult Add(GratefulnessViewModel model)
        {

            if (ModelState.IsValid)
            {

                if (model.GratefulnessEntry.GratefulnessEntryID == 0)
                {
                    GratefulnessEntry entry = model.GratefulnessEntry;
                    entry.GratefulnessUnits = new List<GratefulnessUnit>();
                    for (int i = 0; i < model.GratefulnessUnits.Count; i++)
                    {
                        entry.GratefulnessUnits.Add(model.GratefulnessUnits[i]);
                    }
                    context.GratefulnessEntries.Add(entry);
                }
                else
                {
                    for (int i = 0; i < model.GratefulnessUnits.Count; i++)
                    {
                        context.GratefulnessUnits.Update(model.GratefulnessUnits[i]);

                    }
                    
                }
            context.SaveChanges();
            return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Action = "Save";
                return View("AddUpdate", model);
            }
        }

        public IActionResult Delete(int id)
        {
            GratefulnessEntry entry = context.GratefulnessEntries.Find(id);
            List<GratefulnessUnit> units = context.GratefulnessUnits.Where(u => u.GratefulnessEntryID == entry.GratefulnessEntryID).ToList();
            context.GratefulnessEntries.Remove(entry);
            context.GratefulnessUnits.RemoveRange(units);
            context.SaveChanges();
            return RedirectToAction("List");
        }


    }
}

PersonalWebTool_V1.2/Areas/Admin/Views/Gratefulness/AddUpdate.cshtml
@model GratefulnessViewModel
@{
    string title = $"Add entry for today {DateTime.Now.ToString()}";
    ViewBag.Title = title;
}

<h1>@ViewBag.Title</h1>

<form autocomplete="off" method="post" asp-area="Admin" asp-controller="Gratefulness" asp-action="Add">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label>Date Created:</label>
        <p>@DateTime.Now.ToString()</p>
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="@Model.GratefulnessEntry.GratefulnessEntryID" />
    </div>
    <div class="grat-in-units">
        @for (int i = 0; i < Model.GratefulnessUnits.Count; i++)
        {
            <div class="grat-in-unit">
                <input type="hidden" asp-for="@Model.GratefulnessUnits[i].GratefulnessUnitID" />
                <input type="hidden" asp-for="@Model.GratefulnessUnits[i].GratefulnessEntryID" />
                <div class="form-group">
                    <label asp-for="@Model.GratefulnessUnits[i].Main">Main thing:</label><br />
                    <input asp-for="@Model.GratefulnessUnits[i].Main" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.GratefulnessUnits[i].Details">Why is that here:</label><br />
                    <textarea rows="4" asp-for="@Model.GratefulnessUnits[i].Details"></textarea>
                </div>
            </div>
        }
    </div>
    <button type="submit" class="btn btn-primary">Add entry</button>
    <a asp-controller="Gratefulness" asp-action="List" class="btn btn-primary">Cancel</a>
</form>

PersonalWebTool_V1.2/Areas/Admin/Views/Gratefulness/Index.cshtml
You added entry to db

PersonalWebTool_V1.2/Areas/Admin/Views/Gratefulness/List.cshtml
@model List<GratefulnessEntry>

@{ViewBag.Title = "Gratefulness Diary";}

<h1>@ViewBag.Title</h1>
<div>
    <a asp-controller="Gratefulness" asp-action="Add">Add new entry</a>

    @foreach (GratefulnessEntry entry in Model)
    {
        <div class="grat-entry">
            <h3 class="grat-date">
                @entry.DateCreated.ToShortDateString()
            </h3>
            <div><a asp-controller="Gratefulness" asp-action="Update" asp-route-id="@entry.GratefulnessEntryID" class="grat-button">Change</a></div>
            <div><a asp-controller="Gratefulness" asp-action="Delete" asp-route-id="@entry.GratefulnessEntryID" class="grat-button">Delete</a></div>
            <div class="grat-units">
                @foreach (GratefulnessUnit unit in entry.GratefulnessUnits)
                {
                    <div class="grat-unit">
                        <h5 class="grat-main">@unit.Main</h5>
                        <div class="grat-details">@unit.Details</div>
                    </div>
                }
            </div>
        </div>
    }
</div>

PersonalWebTool_V1.2/Areas/Admin/Views/Gratefulness/Update.cshtml
@model GratefulnessViewModel