PersonalWebTool_V1.2/Models/HabitDay.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Models
{
    public class HabitDay
    {
        public int HabitDayID { get; set; }
        public DateTime DateCreated { get; set; }
        public int? Points { get; set; }
        public ICollection<HabitQuantity> HabitQuantities { get; set; }
        public HabitDay()
        {
            this.DateCreated = DateTime.Now;
        }
    }
}

PersonalWebTool_V1.2/Areas/Admin/Controllers/HabitDayController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebTool_V1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalWebTool_V1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HabitDayController : AdminController
    {
        private BlogContext context;
        public HabitDayController(BlogContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            DateTime Today = DateTime.Now.Date;
            DateTime LastHabitDay = context.HabitDays.OrderByDescending(h => h.HabitDayID).First().DateCreated;
            if (Today.Date > LastHabitDay.Date)
            {
                return RedirectToAction("MakeNewForPast");
            }
            else
            {
                HabitViewModel model = new HabitViewModel();
                model.HabitDays = context.HabitDays.OrderByDescending(h => h.DateCreated).ToList();
                model.Habits = context.Habits.OrderBy(h => h.HabitID).ToList();
                model.HabitQuantities = context.HabitQuantities.OrderBy(q => q.Habit.HabitID).ToList();
                return View(model);
            }
        }

        public IActionResult MakeNew()
        {

            HabitDay currentDay = new HabitDay();
            context.Add(currentDay);
            context.SaveChanges();
            foreach (Habit habit in context.Habits)
            {
                string ID = currentDay.HabitDayID + "-" + habit.HabitID;
                HabitQuantity habitQuantity = new HabitQuantity();
                habitQuantity.HabitQuantityID = ID;
                habitQuantity.Habit = habit;
                habitQuantity.HabitDay = currentDay;
                habitQuantity.Counter = 0;
                context.HabitQuantities.Add(habitQuantity);
            }
            context.SaveChanges();
            return RedirectToAction("List");
        }

        public IActionResult MakeNewForPast()
        {
            DateTime Today = DateTime.Now.Date;
            DateTime LastHabitDayDate = context.HabitDays.OrderBy(h => h.DateCreated).Last().DateCreated.Date;
            int DaysBetween = Today.Subtract(LastHabitDayDate).Days;
            DateTime[] DaysToFill = new DateTime[DaysBetween];
            DateTime DateToFill = LastHabitDayDate.AddDays(1);
            for (int i = 0; i < DaysBetween; i++)
            {
                DaysToFill[i] = DateToFill;
                DateToFill = DateToFill.AddDays(1);
            }
            foreach (DateTime day in DaysToFill)
            {
                HabitDay currentDay = new HabitDay();
                currentDay.DateCreated = day;
                context.Add(currentDay);
                context.SaveChanges();
                foreach (Habit habit in context.Habits)
                {
                    string ID = currentDay.HabitDayID + "-" + habit.HabitID;
                    HabitQuantity habitQuantity = new HabitQuantity();
                    habitQuantity.HabitQuantityID = ID;
                    habitQuantity.Habit = habit;
                    habitQuantity.HabitDay = currentDay;
                    habitQuantity.Counter = 0;
                    context.HabitQuantities.Add(habitQuantity);
                }
            }
            context.SaveChanges();
            return RedirectToAction("List");
        }


        public IActionResult AddPoint(string id)
        {
            string[] slug = id.Split("-");
            string habitID = slug[0];
            string habitDayID = slug[1];
            HabitQuantity habitQuantity = context.HabitQuantities.Where(q => q.Habit.HabitID.ToString() == habitID && q.HabitDay.HabitDayID.ToString() == habitDayID).FirstOrDefault();
            habitQuantity.Counter++;
            context.HabitQuantities.Update(habitQuantity);
            context.SaveChanges();
            return RedirectToAction("List");

        }

        public IActionResult DeletePoint(string id)
        {
            string[] slug = id.Split("-");
            string habitID = slug[0];
            string habitDayID = slug[1];
            HabitQuantity habitQuantity = context.HabitQuantities.Where(q => q.Habit.HabitID.ToString() == habitID && q.HabitDay.HabitDayID.ToString() == habitDayID).FirstOrDefault();
            habitQuantity.Counter--;
            context.HabitQuantities.Update(habitQuantity);
            context.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

PersonalWebTool_V1.2/Areas/Admin/Views/HabitDay/List.cshtml
@model HabitViewModel
@{ViewBag.Title = "HabitDAYZ";}

<h1>@ViewBag.Title</h1>
<div>
    <a asp-controller="HabitDay" asp-action="MakeNew">Make new habit day</a>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Date</th>
                @foreach (Habit habit in Model.Habits)
                {
                    <th>@habit.Name (@habit.Points pts.)</th>
                }
                <th>Summary for day</th>

            </tr>
        </thead>
        <tbody class="habit-table">
            @foreach (HabitDay habitDay in Model.HabitDays)
            {
                int sumOfPoints = 0;
                <tr>
                    <td>@habitDay.DateCreated.ToShortDateString()</td>
                    @foreach (HabitQuantity quantity in Model.HabitQuantities.Where(q => q.HabitDay == habitDay))
                    {
                        sumOfPoints += quantity.Counter * quantity.Habit.Points;
                        string id = quantity.Habit.HabitID + "-" + habitDay.HabitDayID;
                        <td>
                            <h5 class="quantity-counter">
                                @quantity.Counter
                            </h5>
                            <div class="point-buttons">
                                <a class="plus-point" asp-controller="HabitDay" asp-action="AddPoint" asp-route-id="@id">
                                    <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                </a>
                                <a class="minus-point" asp-controller="HabitDay" asp-action="DeletePoint" asp-route-id="@id">
                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                    }
                    <td class="sum-of-points">@sumOfPoints Points</td>

                </tr>
            }
        </tbody>
    </table>
</div>